name: Test

on: [push, pull_request]

jobs:
  biome:
    name: Biome

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check
        run: ./node_modules/.bin/biome ci

  typescript:
    name: Type check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Type check
        run: ./node_modules/.bin/tsc --noEmit
